media_folder: /srv/media
webserver:
  url: localhost/backend
  redis_host: localhost
  redis_port: 6379
shotdetection:
  host: devbox2.research.tib.eu
  port: 52051
facedetection:
  host: devbox2.research.tib.eu
  port: 52052
