data_dir: /data
plugins:
  - plugin: video_to_audio
    params: 
      host: analyser_redisai
  - plugin: thumbnail_generator
    params: 
      host: analyser_redisai
  - plugin: audio_amp_analysis
    params: 
      host: analyser_redisai
  - plugin: audio_freq_analysis
    params: 
      host: analyser_redisai
  - plugin: transnet_shotdetection
    params: 
      host: analyser_redisai
  - plugin: insightface_detector
    params: 
      host: analyser_redisai
  - plugin: insightface_facesize
    params: 
      host: analyser_redisai
  - plugin: deepface_emotion
    params: 
      host: analyser_redisai
  - plugin: shot_type_classifier
    params: 
      host: analyser_redisai
  - plugin: color_analyser
    params: 
      host: analyser_redisai
  - plugin: clip_image_embedding
    params: 
      host: analyser_redisai
  - plugin: clip_text_embedding
    params: 
      host: analyser_redisai
  - plugin: clip_probs
    params: 
      host: analyser_redisai
  - plugin: places_classifier
    params: 
      host: analyser_redisai
  - plugin: shot_annotator
    params: 
      host: analyser_redisai
