data:
  data_dir: /data
  cache:
      type: redis
      params:
        db: 0
        host: analyser_redis
        port: 6379
        tag: data_test
plugins:
  - plugin: aggregate_scalar
  - plugin: aggregate_scalar_per_time
  - plugin: cosine_similarity
  - plugin: video_to_audio
  - plugin: audio_amp_analysis
  - plugin: audio_rms_analysis
  - plugin: audio_freq_analysis
  - plugin: color_analyser
  - plugin: color_brightness_analyser
  - plugin: shot_scalar_annotator
  - plugin: shot_density
  - plugin: shot_annotator
  - plugin: thumbnail_generator
  - plugin: insightface_facesize
  - plugin: x_clip_video_embedding
    params:
      inference:
        type: bentoml
        params:
          host: inference
          port: 3000
          service: x_clip_video
  - plugin: x_clip_text_embedding
    params:
      inference:
        type: bentoml
        params:
          host: inference
          port: 3000
          service: x_clip_text
  - plugin: x_clip_probs
    params:
      text_inference:
        type: bentoml
        params:
          host: inference
          port: 3000
          service: x_clip_text
      sim_inference:
        type: bentoml
        params:
          host: inference
          port: 3000
          service: x_clip_sim
  - plugin: clip_image_embedding
    params:
      inference:
        type: bentoml
        params:
          host: inference
          port: 3000
          service: clip_image_encoder
  - plugin: clip_text_embedding
    params:
      inference:
        type: bentoml
        params:
          host: inference
          port: 3000
          service: clip_text_encoder
  - plugin: clip_probs
  - plugin: transnet_shotdetection
    params:
      inference:
        type: bentoml
        params:
          host: inference
          port: 3000
          service: transnet
  - plugin: shot_type_classifier
    params:
      inference:
        type: bentoml
        params:
          host: inference
          port: 3000
          service: shot_type_classification
  - plugin: places_classifier
    params:
      inference:
        type: bentoml
        params:
          host: inference
          port: 3000
          service: places_classification
  - plugin: insightface_video_detector_torch
    params:
      inference:
        type: bentoml
        params:
          host: inference
          port: 3000
          service: insightface_detector
  - plugin: insightface_image_detector_torch
    params:
      inference:
        type: bentoml
        params:
          host: inference
          port: 3000
          service: insightface_detector
  - plugin: deepface_emotion
    params:
      inference:
        type: bentoml
        params:
          host: inference
          port: 3000
          service: deepface_emotion
  - plugin: insightface_video_feature_extractor
    params:
      inference:
        type: bentoml
        params:
          host: inference
          port: 3000
          service: insightface_feature_extraction
  - plugin: insightface_image_feature_extractor
    params:
      inference:
        type: bentoml
        params:
          host: inference
          port: 3000
          service: insightface_feature_extraction

  # - plugin: insightface_video_gender_age_calculator
  #   params:
  #     inference:
  #       type: bentoml
  #       params:
  #         host: inference
  #         port: 3000
  #         service: insightface_genderage
  # - plugin: insightface_image_gender_age_calculator
  #   params:
  #     inference:
  #       type: bentoml
  #       params:
  #         host: inference
  #         port: 3000
  #         service: insightface_genderage