data_dir: /data
plugins:
  - plugin: video_to_audio
    params:
      data_dir: /data
  - plugin: thumbnail_generator
    params:
      data_dir: /data
  - plugin: audio_amp_analysis
    params: {}
  - plugin: transnet_shotdetection
    params: {}
  - plugin: insightface_detector
    params: {}
