version: "3.4"

networks:
  tibava:
    name: tibava_network

services:
  tibava:
    image: tibava
    networks:
      - tibava
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./media
        target: /app/media
  shotdetection:
    image: shotdetection
    networks:
      - tibava
    build:
      context: shotdetection
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
    volumes:
      - type: bind
        source: ./media
        target: /app/media
  facedetection:
    image: facedetection
    networks:
      - tibava
    build:
      context: facedetection
      dockerfile: ./Dockerfile
    ports:
      - 5002:5002
    volumes:
      - type: bind
        source: ./media
        target: /app/media
