version: "3.4"

# networks:
#   tibava:
#     name: tibava_network

services:
  tibava:
    image: tibava
    # networks:
    #   - tibava
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    # ports:
    #   - 5000:5000
    volumes:
      - type: bind
        source: ./
        target: /app
  celery:
    image: celery
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile_celery
    volumes:
      - type: bind
        source: ./
        target: /app
  redis:
    image: redis:6.2.1
    network_mode: host
  shotdetection:
    image: shotdetection
    # networks:
    #   - tibava
    build:
      context: shotdetection
      dockerfile: ./Dockerfile
    network_mode: host
    # ports:
    #   - 50051:50051
    volumes:
      - type: bind
        source: ./shotdetection
        target: /app
      - type: bind
        source: ./media_grpc
        target: /media
  facedetection:
    image: facedetection
    # networks:
    #   - tibava
    build:
      context: facedetection
      dockerfile: ./Dockerfile
    network_mode: host
    # ports:
    #   - 5002:5002
    volumes:
      - type: bind
        source: ./facedetection
        target: /app
      - type: bind
        source: ./media_grpc
        target: /media
