data:
  data_dir: /data
  cache:
      type: redis
      params:
        db: 1
        host: backend_redis
        port: 6380
        tag: analyser
inference:
  type: ray
  params: 
    host: inference_ray
    port: 8000
    status_port: 52365
